[project]
name = "marocao-platform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.18.5",
    "apscheduler>=3.11.3",
    "argon2-cffi>=25.1.0",
    "beautifulsoup4>=4.15.0",
    "charset-normalizer>=3.4.9",
    "chromadb>=1.5.9",
    "fastapi>=0.138.1",
    "httpx>=0.28.1",
    "langchain-text-splitters>=1.1.2",
    "onnxruntime>=1.28.0",
    "openpyxl>=3.1.5",
    "paddlepaddle>=3.3.1",
    "pandas>=3.0.3",
    "pdf2image>=1.17.0",
    "psutil>=7.2.2",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.15.0",
    "pydantic[email]>=2.13.4",
    "pyjwt>=2.13.0",
    "pymupdf>=1.28.0",
    "pypdf>=6.14.2",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.32",
    "rapidocr-onnxruntime>=1.4.4",
    "reportlab>=5.0.0",
    "selenium>=4.45.0",
    "sentence-transformers>=5.7.0",
    "sqlalchemy>=2.0.51",
    "torch>=2.13.0",
    "ultralytics>=8.4.113",
    "uvicorn>=0.49.0",
    "xlrd>=2.0.2",
]
