"""add_scraping_metrics_columns_to_tenders

Revision ID: 23cb4e19a429
Revises: 886e015a57a5
Create Date: 2026-08-04 12:48:19.352103

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23cb4e19a429'
down_revision: Union[str, Sequence[str], None] = '886e015a57a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

scraping_status_enum = sa.Enum(
    'SUCCESS', 'PENDING', 'IN_PROGRESS', 'SELENIUM_ERROR', 'DOWNLOAD_ERROR',
    name='scrapingstatus'
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    scraping_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        'tenders',
        sa.Column(
            'scraping_status',
            scraping_status_enum,
            nullable=False,
            server_default='PENDING'
        )
    )
    
    op.add_column('tenders', sa.Column('scraping_duration_sec', sa.Float(), nullable=True))
    
    op.add_column(
        'tenders',
        sa.Column(
            'is_zip_corrupted',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false')
        )
    )
    
    op.add_column('tenders', sa.Column('scraping_error_message', sa.Text(), nullable=True))

    op.create_index(op.f('ix_tenders_is_zip_corrupted'), 'tenders', ['is_zip_corrupted'], unique=False)
    op.create_index(op.f('ix_tenders_scraping_status'), 'tenders', ['scraping_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_scraping_status'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_is_zip_corrupted'), table_name='tenders')
    op.drop_column('tenders', 'scraping_error_message')
    op.drop_column('tenders', 'is_zip_corrupted')
    op.drop_column('tenders', 'scraping_duration_sec')
    op.drop_column('tenders', 'scraping_status')
    # ### end Alembic commands ###
