"""add_model_raglog

Revision ID: 3501567382fc
Revises: 7ae8b98744ad
Create Date: 2026-08-12 14:03:41.728027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3501567382fc'
down_revision: Union[str, Sequence[str], None] = '7ae8b98744ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('tender_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['tender_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_logs_created_at'), 'rag_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_logs_document_id'), 'rag_logs', ['document_id'], unique=False)
    op.create_index(op.f('ix_rag_logs_event'), 'rag_logs', ['event'], unique=False)
    op.create_index(op.f('ix_rag_logs_stage'), 'rag_logs', ['stage'], unique=False)
    op.create_index(op.f('ix_rag_logs_tender_id'), 'rag_logs', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_logs_tender_id'), table_name='rag_logs')
    op.drop_index(op.f('ix_rag_logs_stage'), table_name='rag_logs')
    op.drop_index(op.f('ix_rag_logs_event'), table_name='rag_logs')
    op.drop_index(op.f('ix_rag_logs_document_id'), table_name='rag_logs')
    op.drop_index(op.f('ix_rag_logs_created_at'), table_name='rag_logs')
    op.drop_table('rag_logs')
    # ### end Alembic commands ###
