"""add_analysis_metadata_to_tender_documents

Revision ID: 37eefcdd9516
Revises: 9a141a823fd7
Create Date: 2026-07-19 01:40:11.592102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37eefcdd9516'
down_revision: Union[str, Sequence[str], None] = '9a141a823fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_documents', sa.Column('analysis_metadata', sa.JSON(), nullable=True, comment='Métriques et détails techniques de la classification IA'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_documents', 'analysis_metadata')
    # ### end Alembic commands ###
