"""add_summary_to_rag_analysis

Revision ID: 3a3b4bcc3734
Revises: 3501567382fc
Create Date: 2026-08-12 16:39:45.440841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3b4bcc3734'
down_revision: Union[str, Sequence[str], None] = '3501567382fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_analysis_results', sa.Column('summary', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_analysis_results', 'summary')
    # ### end Alembic commands ###
