"""add_indexes_to_tender_model

Revision ID: 3d674e2f193a
Revises: d93b2feec39f
Create Date: 2026-07-15 16:57:39.978067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d674e2f193a'
down_revision: Union[str, Sequence[str], None] = 'd93b2feec39f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tenders_categorie'), 'tenders', ['categorie'], unique=False)
    op.create_index(op.f('ix_tenders_deadline'), 'tenders', ['deadline'], unique=False)
    op.create_index(op.f('ix_tenders_extraction_date'), 'tenders', ['extraction_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_extraction_date'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_deadline'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_categorie'), table_name='tenders')
    # ### end Alembic commands ###
