"""add extracted_text_to_rag_analysis_results

Revision ID: 4f0bf322de97
Revises: 734e0fd125a4
Create Date: 2026-08-07 11:47:17.747870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f0bf322de97'
down_revision: Union[str, Sequence[str], None] = '734e0fd125a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
