"""add extracted_text_to_rag_analysis_results

Revision ID: 5e571b47021f
Revises: 4f0bf322de97
Create Date: 2026-08-07 11:48:01.978551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e571b47021f'
down_revision: Union[str, Sequence[str], None] = '4f0bf322de97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_analysis_results', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_analysis_results', 'extracted_text')
    # ### end Alembic commands ###
