"""add classified_file_path to tender_documents

Revision ID: 64b9f5c8dc4b
Revises: 761c10675040
Create Date: 2026-07-17 19:11:37.752655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b9f5c8dc4b'
down_revision: Union[str, Sequence[str], None] = '761c10675040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_documents', sa.Column('classified_file_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_documents', 'classified_file_path')
    # ### end Alembic commands ###
