"""add_tender_preparation

Revision ID: 6f3c4391a299
Revises: 3a3b4bcc3734
Create Date: 2026-08-13 12:00:19.083091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f3c4391a299'
down_revision: Union[str, Sequence[str], None] = '3a3b4bcc3734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_preparations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SCANNING', 'REVIEW', 'READY', 'FINALIZED', 'FAILED', name='preparationstatus'), nullable=False),
    sa.Column('can_finalize', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tender_id')
    )
    op.create_index(op.f('ix_tender_preparations_status'), 'tender_preparations', ['status'], unique=False)
    op.create_table('tender_preparation_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('preparation_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('generated_document_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'VALID', 'INVALID', 'DELETED', 'GENERATED', 'FILLED', 'SIGNED', 'READY', name='preparationdocumentstatus'), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_user_provided', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('is_signed', sa.Boolean(), nullable=False),
    sa.Column('is_filled', sa.Boolean(), nullable=False),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['tender_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_document_id'], ['generated_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['preparation_id'], ['tender_preparations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_preparation_documents_document_type'), 'tender_preparation_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_tender_preparation_documents_preparation_id'), 'tender_preparation_documents', ['preparation_id'], unique=False)
    op.create_index(op.f('ix_tender_preparation_documents_status'), 'tender_preparation_documents', ['status'], unique=False)
    op.add_column('generated_documents', sa.Column('source_document_id', sa.UUID(), nullable=True))
    op.alter_column('generated_documents', 'is_custom_template',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('generated_documents', 'is_fallback_used',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment=None,
               existing_comment='True si les modèles standards Waraq ont été utilisés')
    op.create_foreign_key(None, 'generated_documents', 'tender_documents', ['source_document_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'generated_documents', type_='foreignkey')
    op.alter_column('generated_documents', 'is_fallback_used',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment='True si les modèles standards Waraq ont été utilisés')
    op.alter_column('generated_documents', 'is_custom_template',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('generated_documents', 'source_document_id')
    op.drop_index(op.f('ix_tender_preparation_documents_status'), table_name='tender_preparation_documents')
    op.drop_index(op.f('ix_tender_preparation_documents_preparation_id'), table_name='tender_preparation_documents')
    op.drop_index(op.f('ix_tender_preparation_documents_document_type'), table_name='tender_preparation_documents')
    op.drop_table('tender_preparation_documents')
    op.drop_index(op.f('ix_tender_preparations_status'), table_name='tender_preparations')
    op.drop_table('tender_preparations')
    # ### end Alembic commands ###
