"""Add RAG Analysis and Generated Docs models

Revision ID: 734e0fd125a4
Revises: 9ae387d0ef41
Create Date: 2026-08-06 21:12:22.091134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '734e0fd125a4'
down_revision: Union[str, Sequence[str], None] = '9ae387d0ef41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('ACTE_ENGAGEMENT', 'DECLARATION_HONNEUR', 'BDP_COMPLETED', 'SYNTHESE_CONFORMITE', name='generateddoctype'), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('is_custom_template', sa.Boolean(), nullable=True),
    sa.Column('is_fallback_used', sa.Boolean(), nullable=True, comment='True si les modèles standards Waraq ont été utilisés'),
    sa.Column('generation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rag_analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INDEXING', 'ANALYZING', 'COMPLETED', 'FAILED', name='ragstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rag_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('indexing_duration_sec', sa.Float(), nullable=True),
    sa.Column('retrieval_duration_sec', sa.Float(), nullable=True),
    sa.Column('generation_duration_sec', sa.Float(), nullable=True),
    sa.Column('total_rag_duration_sec', sa.Float(), nullable=True),
    sa.Column('embedding_duration_sec', sa.Float(), nullable=True),
    sa.Column('llm_extraction_duration_sec', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('embedding_model_used', sa.String(), nullable=False),
    sa.Column('chroma_collection_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['tender_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_index(op.f('ix_rag_analysis_results_status'), 'rag_analysis_results', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_analysis_results_status'), table_name='rag_analysis_results')
    op.drop_table('rag_analysis_results')
    op.drop_table('generated_documents')
    # ### end Alembic commands ###
