"""add classification description and timestamp fields

Revision ID: 761c10675040
Revises: d0204b072d40
Create Date: 2026-07-17 18:00:49.686400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761c10675040'
down_revision: Union[str, Sequence[str], None] = 'd0204b072d40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_documents', sa.Column('classification_description', sa.Text(), nullable=True))
    op.add_column('tender_documents', sa.Column('classified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_documents', 'classified_at')
    op.drop_column('tender_documents', 'classification_description')
    # ### end Alembic commands ###
