"""add administrative zones to tender documents

Revision ID: 7ae8b98744ad
Revises: 830bc1bb8d49
Create Date: 2026-08-11 14:33:06.229275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ae8b98744ad'
down_revision: Union[str, Sequence[str], None] = '830bc1bb8d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_documents', sa.Column('administrative_zones', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_documents', 'administrative_zones')
    # ### end Alembic commands ###
