"""add rag processing status fields

Revision ID: 830bc1bb8d49
Revises: 5e571b47021f
Create Date: 2026-08-10 14:32:16.881169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830bc1bb8d49'
down_revision: Union[str, Sequence[str], None] = '5e571b47021f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_documents', sa.Column('rag_processed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_documents', 'rag_processed')
    # ### end Alembic commands ###
