"""add_is_classified_to_tender_documents

Revision ID: 84101ddcec22
Revises: fca7c0f67832
Create Date: 2026-07-17 12:40:28.320581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84101ddcec22'
down_revision: Union[str, Sequence[str], None] = 'fca7c0f67832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_documents', sa.Column('is_classified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_tender_documents_is_classified'), 'tender_documents', ['is_classified'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tender_documents_is_classified'), table_name='tender_documents')
    op.drop_column('tender_documents', 'is_classified')
    # ### end Alembic commands ###
