"""add_inspection_method_to_classification_audit_logs

Revision ID: 886e015a57a5
Revises: fe64599a5e39
Create Date: 2026-07-31 16:23:41.458599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '886e015a57a5'
down_revision: Union[str, Sequence[str], None] = 'fe64599a5e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification_audit_logs', sa.Column('inspection_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classification_audit_logs', 'inspection_method')
    # ### end Alembic commands ###
