"""add_tender_lot_model

Revision ID: 917bc36a4195
Revises: 
Create Date: 2026-07-06 12:11:53.041581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '917bc36a4195'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_lots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_budget', sa.String(), nullable=True),
    sa.Column('provisional_caution', sa.String(), nullable=True),
    sa.Column('variante', sa.String(), nullable=True),
    sa.Column('qualifications', sa.Text(), nullable=True),
    sa.Column('agrements', sa.Text(), nullable=True),
    sa.Column('prospectus_notices', sa.Text(), nullable=True),
    sa.Column('reunion', sa.Text(), nullable=True),
    sa.Column('visite_lieux', sa.Text(), nullable=True),
    sa.Column('env_considerations', sa.Text(), nullable=True),
    sa.Column('reserve_pme', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('company_profiles', 'capital_social',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_constraint(op.f('company_profiles_user_id_fkey'), 'company_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'company_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tender_documents', 'file_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('tenders', 'deadline',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tenders', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_tenders_is_consulted'), 'tenders', ['is_consulted'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_tenders_is_consulted'), table_name='tenders')
    op.alter_column('tenders', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tenders', 'deadline',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tender_documents', 'file_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'company_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('company_profiles_user_id_fkey'), 'company_profiles', 'users', ['user_id'], ['id'])
    op.alter_column('company_profiles', 'capital_social',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_table('tender_lots')
    # ### end Alembic commands ###
