"""add_response_time_to_tender_documents

Revision ID: 9a141a823fd7
Revises: cb35a56d24a3
Create Date: 2026-07-19 01:28:34.656296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a141a823fd7'
down_revision: Union[str, Sequence[str], None] = 'cb35a56d24a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_documents', sa.Column('response_time', sa.Float(), nullable=True, comment='Temps de traitement/réponse en secondes'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_documents', 'response_time')
    # ### end Alembic commands ###
