"""add_columns_to_tenders_document

Revision ID: 9ae387d0ef41
Revises: e84758baa592
Create Date: 2026-08-04 15:10:56.474933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ae387d0ef41'
down_revision: Union[str, Sequence[str], None] = 'e84758baa592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_documents', sa.Column('page_count', sa.Integer(), nullable=True, comment='Nombre total de pages du document'))
    op.add_column('tender_documents', sa.Column('word_count', sa.Integer(), nullable=True, comment='Nombre de mots extraits'))
    op.add_column('tender_documents', sa.Column('file_size_mb', sa.Float(), nullable=True, comment='Taille du document en Mo'))
    op.add_column('tender_documents', sa.Column('ocr_duration_sec', sa.Float(), nullable=True, comment="Temps consacré à l'OCR en secondes"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_documents', 'ocr_duration_sec')
    op.drop_column('tender_documents', 'file_size_mb')
    op.drop_column('tender_documents', 'word_count')
    op.drop_column('tender_documents', 'page_count')
    # ### end Alembic commands ###
