"""add_system_metrics

Revision ID: a031a11c7b98
Revises: 37eefcdd9516
Create Date: 2026-07-19 15:01:22.920598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a031a11c7b98'
down_revision: Union[str, Sequence[str], None] = '37eefcdd9516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('server_and_hardware_health', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('database_status', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scraping_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_id'), 'system_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_id'), table_name='system_metrics')
    op.drop_table('system_metrics')
    # ### end Alembic commands ###
