"""add_validation_fields_to_tender_document

Revision ID: b14f05f172b5
Revises: 850ffa07a733
Create Date: 2026-07-24 09:49:40.230970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14f05f172b5'
down_revision: Union[str, Sequence[str], None] = '850ffa07a733'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_documents', sa.Column('is_validated', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tender_documents', sa.Column('validation_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_documents', 'validation_status')
    op.drop_column('tender_documents', 'is_validated')
    # ### end Alembic commands ###
