"""add nbr_documents to tenders

Revision ID: cb35a56d24a3
Revises: 64b9f5c8dc4b
Create Date: 2026-07-19 00:18:02.102164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb35a56d24a3'
down_revision: Union[str, Sequence[str], None] = '64b9f5c8dc4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. On crée la colonne en acceptant le NULL au début
    op.add_column('tenders', sa.Column('nbr_documents', sa.Integer(), nullable=True))
    
    # 2. On initialise toutes les lignes existantes à 0
    op.execute("UPDATE tenders SET nbr_documents = 0 WHERE nbr_documents IS NULL")
    
    # 3. Maintenant qu'il n'y a plus de NULL, on applique la contrainte NOT NULL
    op.alter_column('tenders', 'nbr_documents', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'nbr_documents')
    # ### end Alembic commands ###
