"""add_classification_reason_to_tender_documents

Revision ID: d0204b072d40
Revises: 84101ddcec22
Create Date: 2026-07-17 15:53:18.488951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0204b072d40'
down_revision: Union[str, Sequence[str], None] = '84101ddcec22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_documents', sa.Column('classification_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender_documents', 'classification_reason')
    # ### end Alembic commands ###
