"""Add classification_audit_logs table

Revision ID: d21f55ba75e3
Revises: e26d577ec8eb
Create Date: 2026-07-22 19:07:52.110938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'd21f55ba75e3'
down_revision: Union[str, Sequence[str], None] = 'e26d577ec8eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_audit_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),  # <--- Changé en UUID
    sa.Column('document_id', postgresql.UUID(as_uuid=True), nullable=False),  # <--- Changé en UUID
    sa.Column('predicted_type', sa.String(), nullable=False),
    sa.Column('classification_reason', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('extracted_keywords', sa.JSON(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=False),
    sa.Column('execution_duration_sec', sa.Float(), nullable=True),
    sa.Column('ollama_total_duration', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('generated_tokens', sa.Integer(), nullable=True),
    sa.Column('text_length_chars', sa.Integer(), nullable=True),
    sa.Column('text_word_count', sa.Integer(), nullable=True),
    sa.Column('has_uncertainty_keywords', sa.Boolean(), nullable=True),
    sa.Column('validation_status', sa.String(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('corrected_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['tender_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classification_audit_logs')
    # ### end Alembic commands ###
