"""add nbr_lots

Revision ID: d93b2feec39f
Revises: 917bc36a4195
Create Date: 2026-07-07 13:50:10.874761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd93b2feec39f'
down_revision: Union[str, Sequence[str], None] = '917bc36a4195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('nbr_lots', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'nbr_lots')
    # ### end Alembic commands ###
