"""add_is_recursive_to_tenders

Revision ID: e26d577ec8eb
Revises: a031a11c7b98
Create Date: 2026-07-20 15:12:42.768215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26d577ec8eb'
down_revision: Union[str, Sequence[str], None] = 'a031a11c7b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenders', sa.Column('is_recursive', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenders', 'is_recursive')
    # ### end Alembic commands ###
