"""add_ai_and_pipeline_to_system_metrics

Revision ID: e84758baa592
Revises: 23cb4e19a429
Create Date: 2026-08-04 13:28:58.717872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e84758baa592'
down_revision: Union[str, Sequence[str], None] = '23cb4e19a429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'system_metrics',
        sa.Column(
            'ai_and_pipeline',
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb")  # <-- Sets empty JSONB as default for existing rows
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_metrics', 'ai_and_pipeline')
    # ### end Alembic commands ###
