"""add_is_scanned_to_classification_audit_logs

Revision ID: fe64599a5e39
Revises: b14f05f172b5
Create Date: 2026-07-31 16:08:35.416465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe64599a5e39'
down_revision: Union[str, Sequence[str], None] = 'b14f05f172b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classification_audit_logs', sa.Column('is_scanned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classification_audit_logs', 'is_scanned')
    # ### end Alembic commands ###
